package com.nexus.GYMPULSE.model.equipment;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "equipment")
public class Equipment {
    @Id
    private String id;           // Unique identifier for the equipment
    private String name;         // Name of the equipment (e.g., Treadmill)
    private String type;         // Type of equipment (e.g., Cardio, Strength)
    private String brand;        // Brand of the equipment
    private int quantity;        // Number of units available
    private boolean available;   // Availability status

    // Constructor, getters, and setters will be generated by Lombok (@Data)
}
